name: Docker Image CI

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Auterion/checkout@v2
    - name: free disk space
      run: df -h /
        && sudo swapoff -a
        && sudo rm -f /swapfile
        && sudo apt clean
        && docker rmi $(docker image ls -aq)
        && df -h /
    - name: Build the Docker image
      env:
        QT_CI_LOGIN: ${{ secrets.QT_CI_LOGIN }}
        QT_CI_PASSWORD: ${{ secrets.QT_CI_PASSWORD }}
      run: docker build . --file Dockerfile_qgc-build-android_arm64_v8a --build-arg QT_CI_LOGIN=$QT_CI_LOGIN --build-arg QT_CI_PASSWORD=$QT_CI_PASSWORD
